import {
	GetStaticProps,
	GetStaticPropsContext,
	InferGetStaticPropsType,
} from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import PokemonApi from '../apis/pokemonApi';
import styles from '../styles/Home.module.css';

export default function PokemonList({ pokemons }: { pokemons: object[] }) {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Pokemons</h1>

				<p className={styles.description}>
					Get started by editing{' '}
					<code className={styles.code}>pages/index.js</code>
				</p>

				<div className={styles.grid}>
					{pokemons.map((pokemon: object) => (
						<Link
							key={pokemon.name}
							href={`/pokemon/${pokemon.name}`}
						>
							<a className={styles.card}>
								<h2>{pokemon.name}</h2>
							</a>
						</Link>
					))}
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image
							src="/vercel.svg"
							alt="Vercel Logo"
							width={72}
							height={16}
						/>
					</span>
				</a>
			</footer>
		</div>
	);
}

export const getStaticProps: GetStaticProps = async (
	context: GetStaticPropsContext
) => {
	const { data } = await PokemonApi.getPokemons();
	const pokemons = data.results;

	return {
		props: { pokemons },
	};
};
